#!/usr/bin/env node

if (process.argv.slice(2).join(" ") !== "-j monitors") process.exit(2);
process.stdout.write(JSON.stringify([{
  id: 0,
  name: "TEST-1",
  x: 0,
  y: 0,
  width: 1920,
  height: 1080,
  scale: 1,
  focused: true
}]));
