#!/usr/bin/env node

process.stdout.write([
  "level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext",
  "5\t1\t1\t1\t1\t1\t0\t0\t1\t1\t96\tCaptured",
  "5\t1\t1\t1\t1\t2\t1\t0\t1\t1\t95\tcontext"
].join("\n"));
